### ISSUE TITLE
Game Breaking Bug!!!

### ISSUE THREAD

**Issue by Catastrophe0123** [syed-saif/bing-o#2]
The site says preparation time is 1 minute but its really 1:30 minutes.

 ## Literally unplayable.

## 0/5

**Comment by syed-saif** [comment]
Hi Catastrophe0123 ! Yes the time difference was intentional as it took different time for different clients to make the post requests, and also to ensure smoothness.
I would love a detailed explanation , cuz "Literally unplayable" is not helping xD.
Give me all the info in points.

**Comment by syed-saif** [comment]
Also sometimes, the issues maybe because of the browser. Try updating your browser and then play. That will solve most of the issues.

**Comment by Catastrophe0123** [comment]
bruh.... i wasn't serious

**Comment by syed-saif** [comment]
then for now, I'll close this issue. bruhh, if its github then its serious xD
