### ISSUE TITLE
'It'S Your Turn' Container is not responsive

### ISSUE THREAD

**Issue by AquamanRanda** [syed-saif/bing-o#3]
When we have a **big user name**, the username in the container is going outside of and it's kinda looking bad. Pls fix and also make it **mobile friendly** soon. Looking forward to the next UI version

**Comment by syed-saif** [comment]
Thanks Aquaman , for going through my project and taking the time for reporting this issue!!
Yes, I forgot to make it responsive as I assumed small names when in development.
Will fix it. Also the mobile version is getting developed as we speak.
